#!/data/data/com.termux/files/usr/bin/bash

# Build a package
# Requires termux-api-package tool

PREFIX="/data/data/com.termux/files/home"
BOOT_DIR=".termux/boot"
ACTION_DIR=".termux-actions"
LAUNCH_DIR="$ACTION_DIR/launch"

VERSION=$(cat manifest.json | grep version | cut -d : -f 2 | sed 's/[", ]//g')
PKG="termux-action_${VERSION}_all.deb"

apt remove termux-action
termux-create-package manifest.json
apt install "./$PKG"

# Ensure our action dirs exist
mkdir -p "$PREFIX/$ACTION_DIR"
mkdir -p "$PREFIX/$LAUNCH_DIR"

# Place termux-action-notification in termux boot dir, if it exists
# to allow it to run on device startup

if [ -d "$PREFIX/$BOOT_DIR" ]; then
    boot_script="$PREFIX/$BOOT_DIR/termux-action-boot"
    echo "termux-action-notification" > $boot_script && chmod +x $boot_script
    echo "added $boot_script"
fi

# Cleanup
rm $PKG
